### ISSUE TITLE
Trade UC04.01.01 -  OfferTrade  

### ISSUE THREAD

**Issue by hammadj** [CMPUT301F15T02/Xperts#22]
[Link to use case] (https://github.com/CMPUT301F15T02/Xperts/wiki/Use-Case:-Trade-with-Friends-(kathb))

> As an borrower, I want to offer a trade with a friend. A trade will consist of an item from the owner's inventory and 0 or more items from the borrower's inventory.

**Comment by kathb** [comment]
trades can be offered through browse trades. There's a bug where if you click the first item it also selects the last one
