### ISSUE TITLE
Trade UC04.08.01 - BrowseMyTrades  

### ISSUE THREAD

**Issue by hammadj** [CMPUT301F15T02/Xperts#23]
[Link to use case] (https://github.com/CMPUT301F15T02/Xperts/wiki/Use-Case:-Trade-with-Friends-(kathb))

> As an owner or borrower, I can browse all past and current trades involving me.

**Comment by kathb** [comment]
This works. Still needs tests though

**Comment by DavidSkrundz** [comment]
State is being saved, but in a weird way.  you can use `getState()` to get the state object then check its class.
