### ISSUE TITLE
Trade UC04.06.01 - DeleteTrade  

### ISSUE THREAD

**Issue by hammadj** [CMPUT301F15T02/Xperts#30]
[Link to use case] (https://github.com/CMPUT301F15T02/Xperts/wiki/Use-Case:-Trade-with-Friends-(kathb))

> As a borrower, when composing a trade or counter-trade I can delete the trade

**Comment by kathb** [comment]
The borrower can cancel the trade when they click on it in the outgoing tab on the trades list page
