### ISSUE TITLE
Photographs UC05.01.01 -  AttachPhotographs  

### ISSUE THREAD

**Issue by hammadj** [CMPUT301F15T02/Xperts#32]
[Link to use case] (https://github.com/CMPUT301F15T02/Xperts/wiki/Use-Case:-Photographs-of-Items)

> As an owner, I want to optionally attach photographs of items to the item. Photos are optional for items.

**Comment by SeannMurdock** [comment]
need to write UI tests for this. We can add unlimited photos, only the first photo is displayed. New photos are added to index 0.
