### ISSUE TITLE
Photographs UC05.03.01 -  DeletePhotograph  

### ISSUE THREAD

**Issue by hammadj** [CMPUT301F15T02/Xperts#33]
[Link to use case] (https://github.com/CMPUT301F15T02/Xperts/wiki/Use-Case:-Photographs-of-Items)

> As an owner, I want to delete any attached photograph receipt on an item, so that unclear images can be re-taken.

**Comment by SeannMurdock** [comment]
write now deleting isn't implemented but new photos replace the old one.
