### ISSUE TITLE
Photographs UC05.04.01 -  ImageSizeLimit  

### ISSUE THREAD

**Issue by hammadj** [CMPUT301F15T02/Xperts#34]
[Link to use case] (https://github.com/CMPUT301F15T02/Xperts/wiki/Use-Case:-Photographs-of-Items)

> As a sysadmin, I want each receipt image file to be under 65536 bytes in size.

**Comment by DavidSkrundz** [comment]
done in f99f571dba4233dd83c9b099dda8abb4b7419899
