### ISSUE TITLE
Inventory UC01.01.0 - ViewInventory

### ISSUE THREAD

**Issue by hammadj** [CMPUT301F15T02/Xperts#4]
[Link to user story] (https://github.com/CMPUT301F15T02/Xperts/wiki/Use-Case:-Inventory#inventory)

> US01.02.01
> As an owner, I want to view my inventory and its details.

**Comment by SeannMurdock** [comment]
I needed this to work to help with editing an item from the inventory so I made the view profile activity display the user's service list. We still need a test for it though
