### ISSUE TITLE
Implement Login System and User Emails

### ISSUE THREAD

**Issue by hammadj** [CMPUT301F15T02/Xperts#46]
Make emails mandatory, setup login screen, save email in shared preferences

**Comment by hammadj** [comment]
@DavidSkrundz will implement the model for this and make sure the email is unique when signing up

**Comment by DavidSkrundz** [comment]
model should be good to go

**Comment by hammadj** [comment]
Setup application state and logging in/out as well as modified how we get the local user. 

See commit ad0f0604dde59aa013a46f6972c710c60c1b3404
