### ISSUE TITLE
Write Use Cases for new requirements

### ISSUE THREAD

**Issue by hammadj** [CMPUT301F15T02/Xperts#48]
# New Requirements we are implementing:

## Must Do
**US04.10.01**
As an owner, I can set a trade to complete when the borrower returns the item and the item is now available again.

**US04.11.01**
As an owner or borrower, a trade is considered current and in-progress when the item is borrowed.

**US04.12.01**
As an owner or borrower, I should be able to browse in-progress trades, and complete trades.

## Top Traders (Option 2)
**US12.01.01**
As a user, I should be able to see friends and users who are top-traders. Top traders are users with successful (current, in-progress, and complete) trades. The more successful traders, the more top the trader.

## Item Cloning (Option 2)
**US13.01.01**
As an owner, I should be able to clone another user's item, if I own it or a copy. E.g. I have the same XBOX game as my friend and I don't want to type it in again.

**Comment by kathb** [comment]
still need to do geolocation use cases
