### ISSUE TITLE
Item Cloning UC13.01.01 - CloneService

### ISSUE THREAD

**Issue by META-DREAMER** [CMPUT301F15T02/Xperts#61]
[Link to use case](https://github.com/CMPUT301F15T02/Xperts/wiki/New-Use-Cases#item-cloning-option-2)

> As an owner, I should be able to clone another user's item, if I own it or a copy. E.g. I have the same XBOX game as my friend and I don't want to type it in again.

**Comment by kathb** [comment]
The button of this should be changed because it's currently a settings button.
