### ISSUE TITLE
Inventory UC01.03.01 - AddInventoryService 

### ISSUE THREAD

**Issue by hammadj** [CMPUT301F15T02/Xperts#7]
[Link to use case] (https://github.com/CMPUT301F15T02/Xperts/wiki/Use-Case:-Inventory#inventory)

> As an owner, I want to remove, edit, or add an item to my inventory that I want to share. It will have a name, quantity, quality, category, if I want to share it with others, and comments.

**Comment by SeannMurdock** [comment]
Presently adding a service works when all fields are filled. The service is uploaded to elastic search. Presently there is no way to view that service on the app since the profile/inventory isn't implemented yet.
