### ISSUE TITLE
Inventory UC01.04.01 - EditService 

### ISSUE THREAD

**Issue by hammadj** [CMPUT301F15T02/Xperts#8]
[Link to use case] (https://github.com/CMPUT301F15T02/Xperts/wiki/Use-Case:-Inventory#inventory)

> As an owner, I want to remove, edit, or add an item to my inventory that I want to share. It will have a name, quantity, quality, category, if I want to share it with others, and comments.

**Comment by kathb** [comment]
The action bar back button disappears when you view a service
